# Generated by Django 3.1.6 on 2021-05-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shalandadynamic',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.partner', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='samosvaldynamic',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.partner', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='minipogruzchikdynamic',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.partner', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='gusenichnyjekskavatordynamic',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.partner', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='ekskavatorpogruzchikdynamic',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.partner', verbose_name='Контрагент'),
        ),
    ]
