# Generated by Django 3.1.6 on 2021-05-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20210516_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekskavatorpogruzchikdynamic',
            name='vesdynamic',
        ),
    ]
