# Generated by Django 3.1.6 on 2021-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20210516_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekskavatorpogruzchikdynamic',
            name='ravnokolesnyjdynamic',
            field=models.BooleanField(default=None, null=True, verbose_name='Равно-колесный'),
        ),
    ]
