# Generated by Django 3.1.6 on 2021-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_ekskavatorpogruzchikdynamic_ravnokolesnyjdynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipogruzchikdynamic',
            name='gidromolotdynamic',
            field=models.BooleanField(default=None, null=True, verbose_name='Гидромолот'),
        ),
        migrations.AddField(
            model_name='minipogruzchikdynamic',
            name='gruzopodemnostdynamic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Грузоподъемность'),
        ),
        migrations.AddField(
            model_name='minipogruzchikdynamic',
            name='hoddynamic',
            field=models.BooleanField(default=None, null=True, verbose_name='Ход'),
        ),
        migrations.AddField(
            model_name='minipogruzchikdynamic',
            name='schetkadynamic',
            field=models.BooleanField(default=None, null=True, verbose_name='Щетка'),
        ),
        migrations.AddField(
            model_name='minipogruzchikdynamic',
            name='vesdynamic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='minipogruzchikdynamic',
            name='vilydynamic',
            field=models.BooleanField(default=None, null=True, verbose_name='Вилы'),
        ),
    ]
