# Generated by Django 3.1.6 on 2021-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20210516_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samosvaldynamic',
            name='dlinnadynamic',
        ),
        migrations.AddField(
            model_name='samosvaldynamic',
            name='gruzopodemnostdynamic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Грузоподъемность'),
        ),
        migrations.AddField(
            model_name='samosvaldynamic',
            name='obemdynamic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем'),
        ),
    ]
