# Generated by Django 3.1.6 on 2021-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20210516_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='gusenichnyjekskavatordynamic',
            name='dlinnastrelydynamic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длинна стрелы'),
        ),
    ]
