# Generated by Django 3.1.6 on 2021-05-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('machines', '0009_gusenichnyjekskavatordynamic_dlinnastrelydynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtokrandynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=30, verbose_name='Марка')),
                ('in_work', models.DateField(blank=True, null=True, verbose_name='В работе')),
                ('gruzopodemnostdynamic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Грузоподъемность')),
                ('dlinnastrelydynamic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длинна стрелы')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.partner', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'АК',
                'verbose_name_plural': 'АК',
            },
        ),
    ]
