# Generated by Django 3.1.6 on 2021-05-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='machine_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'machines'), ('model', 'shalandadynamic')), models.Q(('app_label', 'machines'), ('model', 'avtokrandynamic')), models.Q(('app_label', 'machines'), ('model', 'minipogruzchikdynamic')), models.Q(('app_label', 'machines'), ('model', 'samosvaldynamic')), models.Q(('app_label', 'machines'), ('model', 'gusenichnyjekskavatordynamic')), models.Q(('app_label', 'machines'), ('model', 'ekskavatorpogruzchikdynamic')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='order',
            name='machine_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'machines'), ('model', 'shalandadynamic')), models.Q(('app_label', 'machines'), ('model', 'avtokrandynamic')), models.Q(('app_label', 'machines'), ('model', 'minipogruzchikdynamic')), models.Q(('app_label', 'machines'), ('model', 'samosvaldynamic')), models.Q(('app_label', 'machines'), ('model', 'gusenichnyjekskavatordynamic')), models.Q(('app_label', 'machines'), ('model', 'ekskavatorpogruzchikdynamic')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тех.'),
        ),
    ]
